services:
  - type: web
    name: everconnect-api
    runtime: docker
    plan: free
    region: oregon # oregon, ohio, frankfurt, or singapore
    
    dockerfilePath: ./Dockerfile
    dockerContext: .
    
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: PORT
        value: 3001
      
      # Add these in Render dashboard for security
      - key: SUPABASE_URL
        sync: false
      
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
    
    healthCheckPath: /health
    
    autoDeploy: true
    
    # Optional: Set up a custom domain
    # domains:
    #   - everconnect-api.yourdomain.com