services:
  # Web Service
  - type: web
    name: everconnect-api
    runtime: docker
    repo: https://github.com/ranteckgsr/everconnect-api
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: https://lkspowixyoxemnmaetle.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false # Set this in Render dashboard for security
      - key: NODE_ENV
        value: production